import fs from 'node:fs'
import path from 'node:path'
import {
  patchRootfsJsonnet,
  renderBundle,
  renderRsdkArgs,
  shq,
  type BundleFile,
  type Profile,
} from '@rsdk-webui/shared'
import { config } from './config.ts'
import { detectEngine } from './env.ts'
import { ensureBuildTree } from './rsdkTree.ts'

export type BundleResult = {
  dir: string
  args: string[]
  treeDir: string
  rsdkVersion?: string
  files: BundleFile[]
}

function copyDir(src: string, dest: string): void {
  fs.cpSync(src, dest, { recursive: true, dereference: false })
}

/**
 * Materialise a complete, self-contained build bundle.
 *
 * The bundle is the unit of truth shared by every backend: the local container
 * runner and the GitHub Actions workflow both just call `run.sh`.
 */
export async function writeBundle(profile: Profile, dir: string): Promise<BundleResult> {
  const local = profile.backend.kind === 'local-docker' ? profile.backend : null
  const engine = await detectEngine(false, local?.engine)
  if (local && !engine) throw new Error(`容器引擎 ${local.engine} 不可用`)
  const imageRef = local?.image || config.image
  const tree = await ensureBuildTree(false, local ? { image: imageRef, engine: engine! } : {})
  if (!tree.ready) throw new Error(tree.error ?? 'rsdk build tree 不可用')

  fs.rmSync(dir, { recursive: true, force: true })
  fs.mkdirSync(dir, { recursive: true })

  // 1. shadow the image's jsonnet tree, with our hook appended
  const treeDest = path.join(dir, 'rsdk-build')
  copyDir(path.join(tree.path, 'build'), treeDest)
  const stockPath = path.join(treeDest, 'rootfs.jsonnet')
  const patched = patchRootfsJsonnet(fs.readFileSync(stockPath, 'utf8'), profile)
  fs.writeFileSync(stockPath, patched)

  // 2. the generated parts
  const files = renderBundle(profile)
  for (const file of files) {
    const target = path.join(dir, file.path)
    fs.mkdirSync(path.dirname(target), { recursive: true })
    const body =
      typeof file.content === 'string'
        ? file.content
        : Buffer.from(file.content.buffer, file.content.byteOffset, file.content.byteLength)
    fs.writeFileSync(target, body, { mode: file.mode })
    fs.chmodSync(target, file.mode)
  }

  // 3. engine plumbing for the local backend
  const hostEnv = [
    '# generated by rsdk-webui',
    `: "\${RSDK_ENGINE:=${profile.backend.kind === 'gh-actions' ? 'docker' : engine?.kind ?? 'podman'}}"`,
    ': "${RSDK_ENGINE_ARGS_FILE:=engine.args}"',
    `if [[ -z "\${RSDK_IMAGE:-}" ]]; then RSDK_IMAGE=${shq(imageRef)}; fi`,
    `: "\${RSDK_TOOLCHAIN_ID:=${path.basename(tree.path)}}"`,
    `: "\${RSDK_RUN_EXTRA=${local ? engine?.runExtra.join(' ') ?? '' : ''}}"`,
    '',
  ].join('\n')
  fs.writeFileSync(path.join(dir, 'host.env'), hostEnv)
  fs.writeFileSync(
    path.join(dir, 'engine.args'),
    (profile.backend.kind === 'gh-actions' ? [] : engine?.args ?? []).join('\n') + (engine?.args?.length ? '\n' : ''),
  )

  // 4. locally built packages
  //
  // These have to be *copied* in: the build happens in a container (and for the
  // GitHub backend, on another machine) where a symlink to a path on this host
  // resolves to nothing. `--debs` is only added by inner.sh when the directory
  // is actually present, so an empty/absent one degrades to a normal build.
  const debs = profile.packages.localDebsDir
  if (debs && profile.backend.kind === 'gh-actions') {
    // committing hundreds of megabytes of .deb files to a branch is not a
    // reasonable thing to do; the GitHub backend has to build without them
    fs.appendFileSync(
      path.join(dir, 'README.md'),
      `\n> 方案里设置了本地 .deb 目录 ${debs}，但 GitHub Actions 构建会跳过它：` +
        '浏览器/推送无法携带这些包。请改用本机容器构建，或把这些包发布到可访问的 apt 源。\n',
    )
  } else if (debs) {
    const target = path.join(dir, 'debs')
    fs.rmSync(target, { recursive: true, force: true })
    fs.mkdirSync(target, { recursive: true })
    if (fs.existsSync(debs) && fs.statSync(debs).isDirectory()) {
      let bytes = 0
      let count = 0
      for (const entry of fs.readdirSync(debs)) {
        if (!entry.endsWith('.deb')) continue
        const source = path.join(debs, entry)
        if (!fs.statSync(source).isFile()) continue
        fs.copyFileSync(source, path.join(target, entry))
        bytes += fs.statSync(source).size
        count += 1
      }
      fs.appendFileSync(
        path.join(dir, 'README.md'),
        `\n## Local packages\n\n${count} 个 .deb（${(bytes / 1024 / 1024).toFixed(1)} MiB）已复制进 ./debs/ ，` +
          '构建时作为 pin 1999 的本地源加入镜像。\n',
      )
    }
  }

  fs.mkdirSync(path.join(dir, 'work'), { recursive: true })
  fs.writeFileSync(
    path.join(dir, '.gitignore'),
    ['.rsdk-cache/', 'work/', 'host.env', 'engine.args', ''].join('\n'),
  )

  return {
    dir,
    args: renderRsdkArgs(profile),
    treeDir: tree.path,
    rsdkVersion: tree.rsdkVersion,
    files,
  }
}

/** Preview only: no disk writes, no environment probing. */
export function previewBundle(profile: Profile): BundleFile[] {
  return renderBundle(profile, { includeGhWorkflow: true })
}

export function listArtifacts(dir: string, baseUrl: string, sharedWorkDir = false): Array<{ name: string; path: string; size: number; url: string }> {
  const outRoot = path.join(dir, ...(sharedWorkDir ? ['out'] : ['work', 'out']))
  if (!fs.existsSync(outRoot)) return []
  const found: Array<{ name: string; path: string; size: number; url: string }> = []
  const walk = (current: string) => {
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const full = path.join(current, entry.name)
      if (entry.isDirectory()) walk(full)
      else if (entry.isFile()) {
        const stat = fs.statSync(full)
        const rel = path.relative(dir, full)
        found.push({ name: entry.name, path: rel, size: stat.size, url: `${baseUrl}/${rel.split(path.sep).map(encodeURIComponent).join('/')}` })
      }
    }
  }
  walk(outRoot)
  return found.sort((a, b) => b.size - a.size)
}
